config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  get '/save_user_from_api', to: "users#save_user_from_api"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

  def full_name
    return self.name_title + ' ' + self.name_first + ' ' + self.name_last
  end

  def self.search(search)
    if search 
      User.where("lower(name_first) LIKE :search or lower(name_last) LIKE :search", search: "%" + search.downcase + "%") 
    else
      User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users or /users.json
  def index
    @users = User.search(params['search']).paginate(page: params[:page], per_page: 10)
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def save_user_from_api
    User.delete_all
    response = self::getDataFromApi
    array_user = JSON.parse(response)
    error = false
    array_user['results'].each do |user|
      if !self::saveUser(user) 
        error = true        
      end
    end

    if !error
      respond_to do |format|
        format.html { redirect_to users_path, notice: "Atualizado" }
      end
    else
      respond_to do |format|
        format.html { redirect_to users_path, notice: "Ocorreu um erro ao atualizar" }
      end
    end
  
  end

  private
    def getDataFromApi
      return RestClient.get "https://randomuser.me/api", {params: {results: 30, inc: 'gender, email, name, picture', nat: 'br', seed: 'giga', format: 'json'}}
    end

    def saveUser(user)
      @user = User.new
      @user.name_title = user['name']['title']
      @user.name_first = user['name']['first']
      @user.name_last = user['name']['last']
      @user.email = user['email']
      @user.gender = user['gender']
      @user.picture_large = user['picture']['large']
      @user.picture_medium = user['picture']['medium']
      
      response_upload_thumbnail = Cloudinary::Uploader.upload(user['picture']['thumbnail'])
      
      if response_upload_thumbnail
        @user.picture_thumbnail = response_upload_thumbnail['url'] 
      else
        @user.picture_thumbnail = user['picture']['thumbnail']
      end

      @user.save!

      return true
    
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TesteGigaAppV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <!-- As a heading -->
  <nav class="navbar navbar-light bg-dark">
    <span class="navbar-brand mb-0 h1">Eduardo Thomé</span>
    <%= link_to save_user_from_api_path, class: 'btn btn-primary float-right' do %>
      <i class="fa fa-cloud-download-alt"></i> Sincronizar com API
    <% end %>
  </nav>

  <div class="container" id="main">
    <%= yield %>
  </div>

  <div class="footer">
    <div class="container">
      <div class="text-center">Eduardo Cannini Thomé</div>
    </div>
  </div>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name_title, style: "display: block" %>
    <%= form.text_field :name_title %>
  </div>

  <div>
    <%= form.label :name_first, style: "display: block" %>
    <%= form.text_field :name_first %>
  </div>

  <div>
    <%= form.label :name_last, style: "display: block" %>
    <%= form.text_field :name_last %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :postcode, style: "display: block" %>
    <%= form.text_field :postcode %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :date_birth, style: "display: block" %>
    <%= form.date_field :date_birth %>
  </div>

  <div>
    <%= form.label :login, style: "display: block" %>
    <%= form.text_field :login %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :picture_thumbnail, style: "display: block" %>
    <%= form.text_field :picture_thumbnail %>
  </div>

  <div>
    <%= form.label :picture_medium, style: "display: block" %>
    <%= form.text_field :picture_medium %>
  </div>

  <div>
    <%= form.label :picture_large, style: "display: block" %>
    <%= form.text_field :picture_large %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :cell, style: "display: block" %>
    <%= form.text_field :cell %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="row item">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-1 thumb">
        <%= image_tag(user.picture_thumbnail, width: 60) if user.picture_thumbnail %>
      </div>
      <div class="col-md-11">
        <p><strong><%= user.full_name %></strong></p>
        <p><%= user.email %></p>
        <p><small><%= user.gender %></small></p>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h3>Usuários</h3>

<p style="color: green"><%= notice %></p>

<div class="row">
  <%= form_tag(users_path, :method => "get") do %>
    <div class="col-md-10">
      <%= text_field_tag(:search, '', class: 'form-control', placeholder: 'Nome ou sobrenome do usuário') %>
    </div>
    <div class="col-md-2">
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
        <i class="fa fa-search"></i> Pesquisar 
      <% end %>    
    </div>
  <% end %>
</div>

<br><br>
<% if @users %>
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
<% else %>
  Nenhum registro encontrado
<% end %>

<div class="text-center">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>